INSERT INTO tb_category(name, created_at) values ('Books', NOW());
INSERT INTO tb_category(name, created_at) values ('Electronics', NOW());
INSERT INTO tb_category(name, created_at) values ('Computers', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Smartphones', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Clothing', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Sports Equipment', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Tools', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Beauty Products', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Kitchenware', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Music Instruments', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Health Supplements', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Stationery', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Art Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Outdoor Gear', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Gardening Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Office Furniture', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Board Games', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Camping Gear', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Fitness Equipment', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Travel Accessories', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Party Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Craft Supplies', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('DIY Kits', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Educational Toys', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Collectibles', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Vintage Items', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Antiques', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Photography Equipment', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Cosmetics', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Perfumes', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_at) VALUES ('Sunglasses', NOW());
